local mod = dmhub.GetModLoading()

CharacterModifier.RegisterType('aura', "Aura")

CharacterModifier.TypeInfo.aura = {
	init = function(modifier)
		modifier.aura = Aura.Create{}
		modifier.radius = "20"
		modifier.seq = dmhub.GenerateGuid()
	end,

	generateAura = function(modifier, creature, auras)
        if modifier:try_get("conditionFormula", "") ~= "" then
            local passes = GoblinScriptTrue(ExecuteGoblinScript(modifier.conditionFormula, GenerateSymbols(creature), 0, "Aura condition"))
            if not passes then
                return
            end
        end

		local token = dmhub.LookupToken(creature)
        if token == nil or (not token.valid) then
            return
        end
        
		local auraInstance = AuraInstance.new{
			guid = modifier:try_get("seq", "--"),
			casterid = token.id,
			name = modifier.aura.name,
			tokenAttached = true, --tell DMHub this is attached to its caster token.
			symbols = {
				caster = GenerateSymbols(creature),
			},

			aura = modifier.aura,

			area = dmhub.CalculateShape{
				shape = 'radiusfromcreature',
				token = token,
				--let it calculate this from the token.
				--targetPoint = core.Vector3(token.loc.x, token.loc.y, 0),
				range = 100,
				radius = ExecuteGoblinScript(modifier.radius, GenerateSymbols(creature, modifier:try_get("_tmp_symbols")), 0, "Aura radius"),
			},
		}

		auras[#auras+1] = auraInstance
	end,

	createEditor = function(modifier, element)
		local Refresh
		Refresh = function()

			local children = {}

            children[#children+1] = gui.Panel{
                classes = {'formPanel'},
                children = {
                    gui.Label{
                        classes = {'formLabel'},
                        text = "Condition:",
                    },

                    gui.GoblinScriptInput{
                        value = modifier:try_get("conditionFormula", ""),
                        change = function(element, text)
                            modifier.conditionFormula = text
                            Refresh()
                        end,

                        documentation = {
                            domains = modifier:Domains(),
                            help = "This GoblinScript is used to filter whether the aura appears or not.",
                            output = "boolean",
                            examples = {
                                {
                                    script = "level > 5",
                                    text = "The aura will only apply to creatures with a level greater than 5.",
                                },
                                {
                                    script = "true",
                                    text = "The aura will always apply.",
                                },
                            },

                            subject = creature.helpSymbols,
                            subjectDescription = "The creature that generated this aura",
                            symbols = modifier:HelpAdditionalSymbols(),
                        },

                    },

                }
            }

			children[#children+1] = gui.Panel{
				classes = {'formPanel'},
				children = {
					gui.Label{
						classes = {'formLabel'},
						text = 'Radius:',
					},
					gui.GoblinScriptInput{
						value = modifier.radius or "20",
						change = function(element, text)
							modifier.radius = text
							modifier.seq = dmhub.GenerateGuid()
							Refresh()
						end,

						documentation = {
							domains = modifier:Domains(),
							help = string.format("This GoblinScript is used to calculate the radius of the aura generated by this modifier."),
							output = "number",
							examples = {
								{
									script = "10",
									text = "The aura will have a radius of 10 feet",
								},
								{
									script = "5 when level < 11 else 30",
									text = "The aura will have a radius of 5 feet if the creature generating it is lower than level 11. Otherwise it will have a radius of 30 feet.",
								},
							},
							subject = creature.helpSymbols,
							subjectDescription = "The creature that generated this aura",
							symbols = modifier:HelpAdditionalSymbols(),
						},

					},
				}
			}

			children[#children+1] = gui.PrettyButton{
				width = 200,
				height = 50,
				text = "Edit Aura",
				click = function(element)
					element.root:AddChild(modifier.aura:ShowEditDialog{ norelocate = true })
				end,
			}

			element.children = children
		end

		Refresh()
	end,
}
